# SPDX-License-Identifier: MIT-0
---
# tasks file for mesh-roaming-node
- name: Openwrt mesh-roaming configuration
  become: true
  become_user: root
  delegate_to: localhost
  block:
    - name: Configure LAN
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        set network.lan.proto="static"
        set network.lan.ipaddr="{{ inventory_hostname }}"
        set network.lan.netmask="255.255.255.0"
        commit network
        EOF'

    - name: Setup bat0 interface
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        set network.bat0="interface"
        set network.bat0.proto="batadv"
        set network.bat0.routing_algo="BATMAN_V"
        set network.bat0.aggregated_ogms="1"
        set network.bat0.ap_isolation="0"
        set network.bat0.bonding="0"
        set network.bat0.fragmentation="1"
        set network.bat0.gw_mode="off"
        set network.bat0.log_level="0"
        set network.bat0.orig_interval="1000"
        set network.bat0.bridge_loop_avoidance="1"
        set network.bat0.distributed_arp_table="1"
        set network.bat0.multicast_mode="1"
        set network.bat0.network_coding="0"
        set network.bat0.hop_penalty="30"
        set network.bat0.isolation_mark="0x00000000/0x00000000"
        commit network
        EOF'

    - name: Setup batmesh interface
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        set network.batmesh="interface"
        set network.batmesh.proto="batadv_hardif"
        set network.batmesh.master="bat0"
        commit network
        EOF'

    - name: bridge eth0 to bat0
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci add_list network.@device[0].ports="bat0"
        uci commit network'

    - name: Create br-default birdge
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        add network device
        set network.@device[1].name="br-default"
        set network.@device[1].type="bridge"
        add_list network.@device[1].ports="bat0"
        commit network
        EOF'

    - name: Create default interface
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        set network.default="interface"
        set network.default.device="br-default"
        set network.default.proto="static"
        set network.default.ipaddr="192.168.10.2"
        set network.default.netmask="255.255.255.0"
        add_list network.default.dns="1.1.1.1"
        add_list network.default.dns="8.8.8.8"
        commit network
        EOF'

    - name: Configure 5g radio (radio1)
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        set wireless.radio1.band="5g"
        set wireless.radio1.channel="149"
        set wireless.radio1.hwmode="11a"
        set wireless.radio1.htmode="VHT80"
        set wireless.radio1.cell_density="0"
        set wireless.radio1.disabled="0"
        set wireless.radio1.country="US"
        commit wireless
        EOF'

    - name: Delete default Openwrt 5g ap
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci -q delete wireless.default_radio1
        uci commit wireless'

    - name: Configure 2g radio (radio0)
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        set wireless.radio0.band="2g"
        set wireless.radio0.channel="6"
        set wireless.radio0.hwmode="11g"
        set wireless.radio0.htmode="HT20"
        set wireless.radio0.disabled="0"
        set wireless.radio0.country="US"
        commit wireless
        EOF'

    - name: Delete default Openwrt 2g ap
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci -q delete wireless.default_radio0
        uci commit wireless'

    - name: Create 5g mesh interface on radio1
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        set wireless.mesh5="wifi-iface"
        set wireless.mesh5.device="radio1"
        set wireless.mesh5.network="batmesh"
        set wireless.mesh5.mode="mesh"
        set wireless.mesh5.encryption="sae-mixed"
        set wireless.mesh5.mesh_id="{{ meshId }}"
        set wireless.mesh5.mesh_fwding="0"
        set wireless.mesh5.mesh_rssi_threshold="0"
        set wireless.mesh5.key="{{ meshApPass }}"
        commit wireless
        EOF'

    - name: Create 5g AP with WPA3 roaming on radio1
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        set wireless.ap5="wifi-iface"
        set wireless.ap5.device="radio1"
        set wireless.ap5.mode="ap"
        set wireless.ap5.ssid="{{ ap5ssid }}"
        set wireless.ap5.encryption="sae-mixed"
        set wireless.ap5.key="{{ meshApPass }}"
        set wireless.ap5.network="lan"
        set wireless.ap5.ieee80211r="1"
        set wireless.ap5.mobility_domain="4f57"
        set wireless.ap5.ft_over_ds="1"
        set wireless.ap5.ft_psk_generate_local="1"
        set wireless.ap5.ieee80211k="1"
        set wireless.ap5.ieee80211v="1"
        set wireless.ap5.bss_transition="1"
        commit wireless
        EOF'

    - name: Create 2g AP with WPA3 roaming on radio0
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci batch <<EOF
        set wireless.ap2="wifi-iface"
        set wireless.ap2.device="radio0"
        set wireless.ap2.mode="ap"
        set wireless.ap2.ssid="{{ ap2ssid }}"
        set wireless.ap2.encryption="sae-mixed"
        set wireless.ap2.key="{{ meshApPass }}"
        set wireless.ap2.network="lan"
        set wireless.ap2.ieee80211r="1"
        set wireless.ap2.mobility_domain="4f57"
        set wireless.ap2.ft_over_ds="1"
        set wireless.ap2.ft_psk_generate_local="1"
        set wireless.ap2.ieee80211k="1"
        set wireless.ap2.ieee80211v="1"
        set wireless.ap2.bss_transition="1"
        commit wireless
        EOF'

    - name: Disable dhcp
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci set dhcp.lan.ignore=1
        uci commit'

    - name: Disable dnsmasq
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        /etc/init.d/dnsmasq disable'

    - name: Commit changes
      ansible.builtin.shell: |
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        uci commit network
        uci commit wireless'

    - name: Restart network
      ansible.builtin.shell: >
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        /etc/init.d/network restart'

    - name: Reload wifi
      ansible.builtin.shell: >
        sshpass -p '{{ openWrtPass }}' ssh -o StrictHostKeyChecking=no '{{ openWrtUser }}@{{ inventory_hostname }}' '
        wifi reload'
